title: Student
description: "Class of 2026"
owner_name: Ahaan Vaidyanathan
github_username: Ahaanv19 
github_repo: "student" 
baseurl: "/student" 
future: true
remote_theme: jekyll/minima
minima:
  skin: solarized-dark
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
header_pages:
  - documentation/home.md
  - navigation/blog.md
  - navigation/search.md
  # - navigation/about.md